---
permalink: protect-scw/reference_storage_types_supported_by_snapcenter_plug_ins_for_microsoft_windows.html 
sidebar: sidebar 
keywords: Storage types 
summary: SnapCenter は、物理マシンと仮想マシンの両方でさまざまなストレージタイプをサポートしています。ホストに対応したパッケージをインストールする前に、ストレージタイプがサポートされているかどうかを確認する必要があります。 
---
= SnapCenter Plug-in for Microsoft Windowsでサポートされるストレージタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter は、物理マシンと仮想マシンの両方でさまざまなストレージタイプをサポートしています。ホストに対応したパッケージをインストールする前に、ストレージタイプがサポートされているかどうかを確認する必要があります。

Windows Server では、 SnapCenter プロビジョニングとデータ保護がサポートされます。サポートされているバージョンの最新情報については、を参照して https://imt.netapp.com/matrix/imt.jsp?components=116859;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool"^]ください。

|===
| マシン | ストレージタイプ | を使用してプロビジョニング | サポートのメモ 


 a| 
物理サーバ
 a| 
FCセツソクLUN
 a| 
SnapCenterのグラフィカルユーザインターフェイス（GUI）またはPowerShellコマンドレット
 a| 



 a| 
物理サーバ
 a| 
iSCSIセツソクLUN
 a| 
SnapCenter GUIまたはPowerShellコマンドレット
 a| 



 a| 
物理サーバ
 a| 
Storage Virtual Machine（SVM）上のSMB3（CIFS）共有
 a| 
SnapCenter GUIまたはPowerShellコマンドレット
 a| 
プロビジョニングのみがサポートされます。

SnapCenter プロトコルを使用してデータや共有をバックアップすることはできません。



 a| 
VMware VM
 a| 
FCまたはiSCSI HBAで接続されたRDM LUN
 a| 
PowerShellコマンドレット
 a| 



 a| 
VMware VM
 a| 
iSCSIイニシエータによってゲストシステムに直接接続されたiSCSI LUN
 a| 
SnapCenter GUIまたはPowerShellコマンドレット
 a| 



 a| 
VMware VM
 a| 
Virtual Machine File Systems（VMFS）またはNFSデータストア
 a| 
VMware vSphere
 a| 



 a| 
VMware VM
 a| 
SVM 上の SMB3 共有に接続されたゲストシステム
 a| 
SnapCenter GUIまたはPowerShellコマンドレット
 a| 
プロビジョニングのみがサポートされます。

SnapCenter プロトコルを使用してデータや共有をバックアップすることはできません。



 a| 
Hyper-V VM
 a| 
仮想ファイバチャネルスイッチで接続された仮想FC（vFC）LUN
 a| 
SnapCenter GUIまたはPowerShellコマンドレット
 a| 
仮想ファイバチャネルスイッチで接続された仮想FC（vFC）LUNをプロビジョニングするには、Hyper-V Managerを使用する必要があります。


NOTE: Hyper-V のパススルーディスク、およびネットアップストレージでプロビジョニングされた VHD （ x ）でのデータベースのバックアップはサポートされていません。



 a| 
Hyper-V VM
 a| 
iSCSIイニシエータによってゲストシステムに直接接続されたiSCSI LUN
 a| 
SnapCenter GUIまたはPowerShellコマンドレット
 a| 

NOTE: Hyper-V のパススルーディスク、およびネットアップストレージでプロビジョニングされた VHD （ x ）でのデータベースのバックアップはサポートされていません。



 a| 
Hyper-V VM
 a| 
SVM 上の SMB3 共有に接続されたゲストシステム
 a| 
SnapCenter GUIまたはPowerShellコマンドレット
 a| 
プロビジョニングのみがサポートされます。

SnapCenter プロトコルを使用してデータや共有をバックアップすることはできません。


NOTE: Hyper-V のパススルーディスク、およびネットアップストレージでプロビジョニングされた VHD （ x ）でのデータベースのバックアップはサポートされていません。

|===