---
permalink: protect-scc/concept_what_you_can_do_with_the_snapcenter_custom_plug_ins.html 
sidebar: sidebar 
keywords: SnapCenter Custom Plug-ins 
summary: SnapCenter Custom Plug-ins を使用してデータ保護処理を実行できます。 
---
= SnapCenterカスタムプラグインおよびストレージプラグインの機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Custom Plug-ins を使用してデータ保護処理を実行できます。

* カスタムプラグイン *

* データベース、インスタンス、ドキュメント、表領域などのリソースを追加します。
* バックアップを作成します。
* バックアップからリストアします。
* バックアップをクローニングします。
* バックアップ処理のスケジュールを設定します。
* バックアップ、リストア、クローニングの各処理を監視する。
* バックアップ、リストア、クローニングの各処理のレポートを表示します。


* ストレージプラグイン *

ストレージプラグインはデータ保護処理に使用できます。

* ONTAPクラスタ間でストレージボリュームの整合グループSnapshotを作成します。
* 組み込みのプレ/ポストスクリプトフレームワークを使用してカスタムアプリケーションをバックアップ
+
ONTAPボリューム、LUN、またはqtreeをバックアップできます。

* SnapCenterポリシーを使用して、既存のレプリケーション関係（SnapVault / SnapMirror /ユニファイドレプリケーション）を利用して、プライマリで作成されたSnapshotをONTAPセカンダリに更新します。
+
ONTAPのプライマリとセカンダリには、ONTAP FAS、AFF、All SAN Array（ASA）、Select、Cloud ONTAPがあります。

* ONTAPボリューム、LUN、またはファイル全体をリカバリ
+
ブラウズ機能またはインデックス機能が製品に組み込まれていないため、それぞれのファイルパスを手動で指定する必要があります。

+
qtreeまたはディレクトリのリストアはサポートされていませんが、バックアップ範囲がqtreeレベルで定義されている場合にのみ、qtreeのクローニングとエクスポートを実行できます。


