---
permalink: protect-scc/concept_snapcenter_custom_plug_ins_features.html 
sidebar: sidebar 
keywords: Custom Plug-ins features 
summary: SnapCenter は、プラグインアプリケーションと統合されるほか、ストレージシステム上でネットアップのテクノロジと統合されます。Custom Plug-ins の操作には、 SnapCenter のグラフィカルユーザインターフェイスを使用します。 
---
= SnapCenter Custom Plug-ins の特長
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter は、プラグインアプリケーションと統合されるほか、ストレージシステム上でネットアップのテクノロジと統合されます。Custom Plug-ins の操作には、 SnapCenter のグラフィカルユーザインターフェイスを使用します。

* * 統一されたグラフィカル・ユーザー・インターフェイス *
+
SnapCenter のインターフェイスは、すべてのプラグインと環境で標準化され、一貫しています。SnapCenter のインターフェイスから、すべてのプラグインで、バックアップ、リストア、リカバリ、クローニングの各処理を一貫した方法で実行できるほか、ダッシュボードビューで概要を把握したり、ロールベースアクセス制御（ RBAC ）を設定したり、ジョブを監視したりすることができます。

* * 中央管理の自動化 *
+
バックアップ処理のスケジュールを設定したり、ポリシーベースのバックアップ保持を設定したり、リストア処理を実行したりできます。SnapCenter から E メールアラートを送信するように設定して、環境をプロアクティブに監視することもできます。

* *無停止のNetAppスナップショットテクノロジ*
+
SnapCenterでは、NetApp SnapshotテクノロジとSnapCenterカスタムプラグインを使用してリソースがバックアップされます。Snapshotはストレージスペースを最小限しか消費しません。



Custom Plug-ins 機能を使用すると、次のメリットもあります。

* バックアップ、リストア、クローニングのワークフローがサポートされます。
* RBACでサポートされるセキュリティと一元化されたロール委譲
+
クレデンシャルを設定して、許可されたSnapCenterユーザにアプリケーションレベルの権限を付与することもできます。

* NetApp FlexClone テクノロジを使用して、スペース効率に優れたポイントインタイムコピーを作成し、テストまたはデータの抽出を行います
+
クローンを作成するストレージシステムにFlexCloneライセンスが必要です。

* バックアップ作成時に、ONTAPの整合グループ（CG）Snapshot機能がサポートされます。
* 複数のリソースホストで同時に複数のバックアップを実行可能
+
1回の処理では、1つのホスト内のリソースが同じボリュームを共有する場合にSnapshotが統合されます。

* 外部コマンドを使用してSnapshotを作成する機能。
* Windows環境でファイルシステムと整合性のあるSnapshotを作成する機能。

