---
permalink: protect-scc/reference_host_requirements_for_installing_the_snapcenter_plug_in_package_for_linux_scc.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: SnapCenter Plug-ins Package for Linuxをインストールする前に、ホストが要件を満たしていることを確認する必要があります。 
---
= SnapCenter Plug-ins Package for Linuxをインストールするホストの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-ins Package for Linuxをインストールする前に、ホストが要件を満たしていることを確認する必要があります。

|===
| 項目 | 要件 


 a| 
オペレーティングシステム
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server（SLES）




 a| 
ホスト上のSnapCenterプラグイン用の最小RAM
 a| 
1 GB



 a| 
ホスト上のSnapCenterプラグインのインストールとログの最小スペース
 a| 
2 GB


NOTE: 十分なディスクスペースを割り当て、logsフォルダによるストレージ消費量を監視する必要があります。必要なログスペースは、保護対象のエンティティの数とデータ保護処理の頻度によって異なります。十分なディスクスペースがない場合、最近実行した処理のログは作成されません。



 a| 
必要なソフトウェアパッケージ
 a| 
Java 1.8（64ビット）Oracle JavaまたはOpenJDK

Javaを最新バージョンにアップグレードした場合は、/var/opt/snapcenter/spl/etc/spl.propertiesにあるJAVA_HOMEオプションが、正しいJavaバージョンと正しいパスに設定されていることを確認する必要があります。

|===
サポートされているバージョンの最新情報については、を参照してください。 https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT["NetApp Interoperability Matrix Tool"]
